### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fat-tire** [poetic/lux#9]
I see parts of this are licensed as MIT... is it all MIT?

Does it work?  Known bugs, etc?

Thx!

**Comment by RealLukeMartin** [comment]
As a whole, this is not licensed MIT.

It definitely works but as I and the other contributors moved onto Drupal 8 it was left in a semi work-in-progress state. More features and polish could be applied to it for a better finished product feel. As a starter pack though it should get most of the jobs done.

**Comment by fat-tire** [comment]
Sorry- confused.  If it's not all MIT, then what is the license?

(Also, where is the drupal 8 version?)

Tx

**Comment by RealLukeMartin** [comment]
You helped me realize this was license-less, just licensed it under MIT. 

https://github.com/poetic/lux/blob/0.2.x/LICENSE.md
